"""add_created_by_and_user_policy_fk

Revision ID: 05499fe83021
Revises: f763bc43f4b6
Create Date: 2026-03-15 11:26:04.993292

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05499fe83021"
down_revision: Union[str, Sequence[str], None] = "f763bc43f4b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("class_policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.drop_column("max_credentials_per_student")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("class_policy_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_users_class_policy_id", "class_policies", ["class_policy_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_class_policy_id", type_="foreignkey")
        batch_op.drop_column("class_policy_id")

    with op.batch_alter_table("class_policies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("max_credentials_per_student", sa.INTEGER(), nullable=False)
        )
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
