"""add_sign_count_anomaly_to_credential

Revision ID: 07b210094a7b
Revises: bff5d2fd04e8
Create Date: 2026-03-15 02:22:25.085917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b210094a7b'
down_revision: Union[str, Sequence[str], None] = 'bff5d2fd04e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_count_anomaly', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_column('sign_count_anomaly')

    # ### end Alembic commands ###
