"""add_missing_fields_batch1

Revision ID: 644cdcd0465e
Revises: 07b210094a7b
Create Date: 2026-03-15 10:37:29.117355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644cdcd0465e'
down_revision: Union[str, Sequence[str], None] = '07b210094a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manually_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('manually_approved_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manually_approved_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sync_pending', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('network_anomaly', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('gps_is_mock', sa.Boolean(), nullable=False))

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_security_level', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_column('key_security_level')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_column('gps_is_mock')
        batch_op.drop_column('network_anomaly')
        batch_op.drop_column('sync_pending')
        batch_op.drop_column('manually_approved_reason')
        batch_op.drop_column('manually_approved_by')
        batch_op.drop_column('manually_approved')

    # ### end Alembic commands ###
