"""policy_idor_refactor_and_geofence

Revision ID: 948967293d89
Revises: 05499fe83021
Create Date: 2026-03-15 11:53:50.162222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "948967293d89"
down_revision: Union[str, Sequence[str], None] = "05499fe83021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gps_in_geofence", sa.Boolean(), nullable=True))

    with op.batch_alter_table("class_policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("class_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_class_policies_class_id", "classes", ["class_id"], ["id"]
        )

    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_classes_class_policy_id"), type_="foreignkey"
        )
        batch_op.drop_column("class_policy_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_users_class_policy_id"), type_="foreignkey"
        )
        batch_op.drop_column("class_policy_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("class_policy_id", sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_users_class_policy_id"),
            "class_policies",
            ["class_policy_id"],
            ["id"],
        )

    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("class_policy_id", sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_classes_class_policy_id"),
            "class_policies",
            ["class_policy_id"],
            ["id"],
        )

    with op.batch_alter_table("class_policies", schema=None) as batch_op:
        batch_op.drop_constraint("fk_class_policies_class_id", type_="foreignkey")
        batch_op.drop_column("class_id")

    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_column("gps_in_geofence")

    # ### end Alembic commands ###
