"""add_class_policy

Revision ID: cfb426536950
Revises: 644cdcd0465e
Create Date: 2026-03-15 10:40:58.138102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfb426536950"
down_revision: Union[str, Sequence[str], None] = "644cdcd0465e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_policies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("play_integrity_enabled", sa.Boolean(), nullable=False),
        sa.Column("standard_assurance_threshold", sa.Integer(), nullable=False),
        sa.Column("high_assurance_threshold", sa.Integer(), nullable=False),
        sa.Column("present_cutoff_minutes", sa.Integer(), nullable=False),
        sa.Column("late_cutoff_minutes", sa.Integer(), nullable=False),
        sa.Column("max_checkin_retries", sa.Integer(), nullable=False),
        sa.Column("max_credentials_per_student", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("class_policy_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_classes_class_policy_id", "class_policies", ["class_policy_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_classes_class_policy_id", type_="foreignkey")
        batch_op.drop_column("class_policy_id")

    op.drop_table("class_policies")
    # ### end Alembic commands ###
