export const ApiPaths = {
	bootstrapStatus: "/bootstrap/status",
	bootstrapOperator: "/bootstrap/operator",
	users: "/users/",
	user: (userId: string) => `/users/${userId}`,
	students: "/students/",
	student: (studentId: string) => `/students/${studentId}`,
	adminRegister: (userId: string) => `/admin/register/${userId}`,
	adminUnregister: (userId: string) => `/admin/unregister/${userId}`,
	adminImportUsers: "/admin/import-users",
	adminImportClasses: "/admin/import-classes",
	adminImportEnrollments: "/admin/import-enrollments",
	adminImportOrgs: "/admin/import-orgs",
	teachers: "/teachers/",
	teacherClasses: (teacherId: string) => `/teachers/${teacherId}/classes`,
	classes: "/classes/",
	class: (classId: string) => `/classes/${classId}`,
	sessions: "/sessions/",
	sessionsByClass: (classId: string) => `/sessions/by-class/${classId}`,
	session: (sessionId: string) => `/sessions/${sessionId}`,
	openSession: "/sessions/open/teacher",
	closeSession: (sessionId: string) => `/sessions/${sessionId}/close`,
	records: "/records/",
	recordsBySession: (sessionId: string) => `/records/by-session/${sessionId}`,
	manualRecord: "/records/manual",
	manualApproval: (recordId: string) => `/records/${recordId}/approve`,
	record: (recordId: string) => `/records/${recordId}`,
	auditEvents: "/audit/",
	auditExport: "/audit/export",
	auditEvent: (eventId: string) => `/audit/${eventId}`,
	policies: "/policies/",
	policy: (policyId: string) => `/policies/${policyId}`,
	userPolicy: (userId: string) => `/policies/user/${userId}`,
	credentials: "/credentials/",
	credential: (credentialId: string) => `/credentials/${credentialId}`,
	enrollments: "/enrollments/",
	enrollment: (enrollmentId: string) => `/enrollments/${enrollmentId}`,
	offlineSync: "/sessions/offline-sync",
	orgs: "/orgs/",
	org: (orgId: string) => `/orgs/${orgId}`,
	orgMembers: (orgId: string) => `/orgs/${orgId}/members`,
	orgMember: (orgId: string, userId: string) =>
		`/orgs/${orgId}/members/${userId}`,
	orgRules: (orgId: string) => `/orgs/${orgId}/rules`,
	orgRule: (orgId: string, ruleId: string) => `/orgs/${orgId}/rules/${ruleId}`,
	events: "/events/",
	orgEvents: (orgId: string) => `/orgs/${orgId}/events/`,
	event: (eventId: string) => `/events/${eventId}`,
	eventRules: (eventId: string) => `/events/${eventId}/rules`,
	eventRule: (eventId: string, ruleId: string) =>
		`/events/${eventId}/rules/${ruleId}`,
	webLoginInitiate: "/auth/web-login/initiate",
	webLoginPoll: (token: string) =>
		`/auth/web-login/poll?token=${encodeURIComponent(token)}`,
	semesters: "/semesters/",
	activeSemester: "/semesters/active",
	semester: (semesterId: string) => `/semesters/${semesterId}`,
} as const;

export const ErrorMessages = {
	apiOriginNotSet: "API origin is not set",
} as const;
