export const ApiPaths = {
	bootstrapOperator: "/bootstrap/operator",
	users: "/users/",
	user: (userId: string) => `/users/${userId}`,
	students: "/students",
	adminRegister: (userId: string) => `/admin/register/${userId}`,
	adminUnregister: (userId: string) => `/admin/unregister/${userId}`,
	teachers: "/teachers",
	classes: "/classes",
	class: (classId: string) => `/classes/${classId}`,
	sessions: "/sessions",
	sessionsByClass: (classId: string) => `/sessions/by-class/${classId}`,
	session: (sessionId: string) => `/sessions/${sessionId}`,
	openSession: "/sessions/open",
	closeSession: (sessionId: string) => `/sessions/${sessionId}/close`,
	records: "/records",
	recordsBySession: (sessionId: string) => `/records/by-session/${sessionId}`,
	manualRecord: "/records/manual",
	manualApproval: (recordId: string) => `/records/${recordId}/approve`,
	record: (recordId: string) => `/records/${recordId}`,
	auditEvents: "/audit",
	auditExport: "/audit/export",
	auditEvent: (eventId: string) => `/audit/${eventId}`,
	policies: "/policies",
	policy: (policyId: string) => `/policies/${policyId}`,
	userPolicy: (userId: string) => `/policies/user/${userId}`,
	credentials: "/credentials/",
	credential: (credentialId: string) => `/credentials/${credentialId}`,
	enrollments: "/enrollments/",
	enrollment: (enrollmentId: string) => `/enrollments/${enrollmentId}`,
} as const;

export const ErrorMessages = {
	apiOriginNotSet: "API origin is not set",
} as const;
